from __future__ import annotations

import builtins
from collections.abc import Iterable

from rich.prompt import Confirm, Prompt


TRANSLATIONS: dict[str, str] = {
    # Generic UI / actions
    "Install": "安装",
    "Run": "运行",
    "Update": "更新",
    "Open Folder": "打开目录",
    "Stop": "停止",
    "Open": "打开",
    "GUI Mode (Download required)": "图形模式（需先下载）",
    "CLI Mode": "命令行模式",
    "Update System": "更新系统",
    "Update Hackingtool": "更新 Hackingtool",
    "Uninstall": "卸载",
    "Troubleshoot": "故障排查",
    "Enter Method": "输入攻击方式",
    "Enter URL": "输入 URL",
    "Enter Threads": "输入线程数",
    "Enter ProxyList": "输入代理列表",
    "Enter Multiple": "输入并发倍数",
    "Enter Timer": "输入持续时间",
    "Enter Target Site": "输入目标站点",
    "Enter Source Port": "输入源端口",
    "Enter Target IP": "输入目标 IP",
    "Enter Target Port": "输入目标端口",
    "Enter target URL": "输入目标 URL",
    "Enter path to memory dump": "输入内存转储文件路径",
    "Enter plugin": "输入插件名",
    "Enter Site": "输入站点",
    "Enter Username": "输入用户名",
    "Enter Wordlist path": "输入字典文件路径",
    "[bold cyan]Enter Website[/bold cyan]": "[bold cyan]输入网站[/bold cyan]",
    "Enter host name (e.g. www.google.com):-  ": "输入主机名（例如 www.google.com）：",
    "Enter Site Name (example.com)": "输入站点名称（example.com）",
    "Enter IP": "输入 IP",
    "Enter domain (example.com)": "输入域名（example.com）",
    "[bold]Select a Target IP[/bold magenta]": "[bold]输入目标 IP[/bold]",
    "Replace it? This removes the existing installation.": "是否替换？这会删除现有安装。",
    "Continue?": "是否继续？",
    "Open guidance link in your browser?": "是否在浏览器中打开说明链接？",
    "Press ENTER to continue": "按回车继续",
    "Enter Url >> ": "输入 URL >> ",
    "Enter (.apk) File >> ": "输入 .apk 文件路径 >> ",
    "[1] Hide\n[2] Extract\n[99]Cancel\n>> ": "[1] 隐藏数据\n[2] 提取数据\n[99] 取消\n>> ",
    "Enter Filename to Embed (1.txt) >> ": "输入要嵌入的文件名（1.txt）>> ",
    "Enter Cover Filename (test.jpeg) >> ": "输入载体文件名（test.jpeg）>> ",
    "Enter Filename to Extract Data From >> ": "输入要提取数据的文件名 >> ",
    "Enter Filename >> ": "输入文件名 >> ",
    "Enter Wordlist Filename >> ": "输入字典文件名 >> ",
    "Enter Username or Emailid (if both then please space between email & username) >> ": "输入用户名或邮箱（若两者都要查，请用空格分隔）>> ",
    # Static console text
    "[bold magenta]Stopping Anonsurf...[/bold magenta]": "[bold magenta]正在停止 Anonsurf...[/bold magenta]",
    "[bold magenta]Cloning repository and attempting to run GUI...[/]": "[bold magenta]正在克隆仓库并尝试启动图形界面...[/]",
    "[magenta]If you get an error after clone go to /java_gui/src/ and compile the .jar file && run ./BEViewer[/]": "[magenta]如果克隆后报错，请进入 /java_gui/src/ 编译 .jar 文件，然后运行 ./BEViewer[/]",
    "[magenta]Please visit for more details about installation: https://github.com/simsong/bulk_extractor[/]": "[magenta]更多安装说明请查看：https://github.com/simsong/bulk_extractor[/]",
    "[magenta]bulk_extractor [options] imagefile[/]": "[magenta]bulk_extractor [options] imagefile[/]",
    "[bold cyan]Requirements:[/bold cyan]\n  - Arduino Software (v1.6.7+)\n  - TeensyDuino\n  - Linux udev rules\n  See: https://github.com/Screetsec/Brutal/wiki/Install-Requirements": "[bold cyan]前置要求：[/bold cyan]\n  - Arduino 软件（v1.6.7+）\n  - TeensyDuino\n  - Linux udev 规则\n  说明见：https://github.com/Screetsec/Brutal/wiki/Install-Requirements",
    "[bold magenta]Vegile commands:[/]\n  Vegile -i / --inject [backdoor/rootkit]\n  Vegile -u / --unlimited [backdoor/rootkit]\n  Vegile -h / --help": "[bold magenta]Vegile 常用命令：[/]\n  Vegile -i / --inject [backdoor/rootkit]\n  Vegile -u / --unlimited [backdoor/rootkit]\n  Vegile -h / --help",
    "[bold red]Please choose a valid input[/bold red]": "[bold red]请输入有效选项[/bold red]",
    "[bold magenta]Set username and password in social_mapper.py before running.[/]\n[magenta]Usage: python social_mapper.py -f <folder> -i <path> -m fast <AcName> -fb -tw[/]": "[bold magenta]运行前请先在 social_mapper.py 中设置用户名和密码。[/]\n[magenta]用法：python social_mapper.py -f <folder> -i <path> -m fast <AcName> -fb -tw[/]",
    "[bold cyan]Usage:[/bold cyan]\n 1. Put interface into monitor mode: [yellow]airmon-ng start <iface>[/yellow]\n 2. Scan: [yellow]wash -i <mon-iface>[/yellow]\n 3. Attack: [yellow]reaver -i <mon-iface> -b <BSSID> -c <ch> -vvv -K 1 -f[/yellow]\n 4. Run: [yellow]pixiewps -h[/yellow]": "[bold cyan]用法：[/bold cyan]\n 1. 将网卡切换到监听模式：[yellow]airmon-ng start <iface>[/yellow]\n 2. 扫描：[yellow]wash -i <mon-iface>[/yellow]\n 3. 发起攻击：[yellow]reaver -i <mon-iface> -b <BSSID> -c <ch> -vvv -K 1 -f[/yellow]\n 4. 查看帮助：[yellow]pixiewps -h[/yellow]",
    # Titles / categories
    "All tools": "全部工具",
    "Anonymously Surf": "匿名浏览",
    "Multitor": "Multitor",
    "Anonymously Hiding Tools": "匿名隐藏工具",
    "Prowler (Cloud Security Scanner)": "Prowler（云安全扫描器）",
    "ScoutSuite (Multi-Cloud Auditing)": "ScoutSuite（多云审计）",
    "Pacu (AWS Exploitation Framework)": "Pacu（AWS 利用框架）",
    "Trivy (Container/K8s Scanner)": "Trivy（容器/K8s 扫描器）",
    "Cloud Security Tools": "云安全工具",
    "BloodHound (AD Attack Paths)": "BloodHound（活动目录攻击路径）",
    "NetExec — nxc (Network Pentesting)": "NetExec — nxc（网络渗透）",
    "Impacket (Network Protocol Tools)": "Impacket（网络协议工具）",
    "Responder (LLMNR/NBT-NS Poisoner)": "Responder（LLMNR/NBT-NS 投毒器）",
    "Certipy (AD Certificate Abuse)": "Certipy（活动目录证书滥用）",
    "Kerbrute (Kerberos Brute Force)": "Kerbrute（Kerberos 暴力破解）",
    "Active Directory Tools": "活动目录工具",
    "DDoS": "DDoS",
    "SlowLoris": "SlowLoris",
    "Asyncrone | Multifunction SYN Flood DDoS Weapon": "Asyncrone | 多功能 SYN Flood DDoS 工具",
    "UFOnet": "UFOnet",
    "GoldenEye": "GoldenEye",
    "SaphyraDDoS": "SaphyraDDoS",
    "DDOS Attack Tools": "DDoS 攻击工具",
    "RouterSploit": "RouterSploit",
    "WebSploit": "WebSploit",
    "Commix": "Commix",
    "Exploit framework": "利用框架",
    "Autopsy": "Autopsy",
    "Wireshark": "Wireshark",
    "Bulk extractor": "Bulk Extractor",
    "Disk Clone and ISO Image Acquire": "磁盘克隆与 ISO 镜像采集",
    "Toolsley": "Toolsley",
    "Volatility 3 (Memory Forensics)": "Volatility 3（内存取证）",
    "Binwalk (Firmware Analysis)": "Binwalk（固件分析）",
    "pspy (Process Monitor — No Root)": "pspy（进程监控，无需 Root）",
    "Forensic tools": "取证工具",
    "Network Map (nmap)": "网络映射（nmap）",
    "Dracnmap": "Dracnmap",
    "Port scanning": "端口扫描",
    "Host to IP ": "域名转 IP",
    "Xerosploit": "Xerosploit",
    "RED HAWK (All In One Scanning)": "RED HAWK（综合扫描）",
    "ReconSpider(For All Scanning)": "ReconSpider（综合扫描）",
    "IsItDown (Check Website Down/Up)": "IsItDown（检查网站是否在线）",
    "Infoga - Email OSINT": "Infoga - 邮箱 OSINT",
    "ReconDog": "ReconDog",
    "Striker": "Striker",
    "SecretFinder (like API & etc)": "SecretFinder（API Key 等敏感信息）",
    "Find Info Using Shodan": "使用 Shodan 查信息",
    "Port Scanner - rang3r": "端口扫描器 - rang3r",
    "Breacher": "Breacher",
    "theHarvester (OSINT)": "theHarvester（OSINT）",
    "Amass (Attack Surface Mapping)": "Amass（攻击面测绘）",
    "Masscan (Fast Port Scanner)": "Masscan（高速端口扫描）",
    "RustScan (Modern Port Scanner)": "RustScan（现代端口扫描器）",
    "Holehe (Email → Social Accounts)": "Holehe（邮箱 → 社交账号）",
    "Maigret (Username OSINT)": "Maigret（用户名 OSINT）",
    "httpx (HTTP Toolkit)": "httpx（HTTP 工具集）",
    "SpiderFoot (OSINT Automation)": "SpiderFoot（OSINT 自动化）",
    "Subfinder (Subdomain Enumeration)": "Subfinder（子域枚举）",
    "TruffleHog (Secret Scanner)": "TruffleHog（密钥扫描器）",
    "Gitleaks (Git Secret Scanner)": "Gitleaks（Git 密钥扫描器）",
    "Information gathering tools": "信息收集工具",
    "MobSF (Mobile Security Framework)": "MobSF（移动安全框架）",
    "Frida (Dynamic Instrumentation)": "Frida（动态插桩）",
    "Objection (Mobile Runtime Exploration)": "Objection（移动运行时探索）",
    "Mobile Security Tools": "移动安全工具",
    "HatCloud(Bypass CloudFlare for IP)": "HatCloud（绕过 CloudFlare 获取真实 IP）",
    "Other tools": "其他工具",
    "Keydroid": "Keydroid",
    "MySMS": "MySMS",
    "Lockphish (Grab target LOCK PIN)": "Lockphish（获取目标锁屏 PIN）",
    "DroidCam (Capture Image)": "DroidCam（抓取图像）",
    "EvilApp (Hijack Session)": "EvilApp（会话劫持）",
    "Android Hacking tools": "Android 攻击工具",
    "Knockmail": "Knockmail",
    "Email Verify tools": "邮箱验证工具",
    "Hash Buster": "Hash Buster",
    "Hash cracking tools": "哈希破解工具",
    "EvilURL": "EvilURL",
    "IDN Homograph Attack": "IDN 同形异义攻击",
    "Terminal Multiplexer": "终端复用器",
    "Crivo": "Crivo",
    "Mix tools": "杂项工具",
    "Debinject": "Debinject",
    "Pixload": "Pixload",
    "Payload Injector": "载荷注入工具",
    "Instagram Attack": "Instagram 攻击",
    "AllinOne SocialMedia Attack": "一体化社交媒体攻击",
    "Facebook Attack": "Facebook 攻击",
    "Application Checker": "应用检查器",
    "SocialMedia Bruteforce": "社交媒体暴力破解",
    "Find SocialMedia By Facial Recognation System": "通过人脸识别查找社交媒体账号",
    "Find SocialMedia By UserName": "按用户名查找社交媒体账号",
    "Sherlock": "Sherlock",
    "SocialScan | Username or Email": "SocialScan | 用户名或邮箱",
    "SocialMedia Finder": "社交媒体查找工具",
    "Gospider": "Gospider",
    "Web crawling": "网页爬取",
    "WifiJammer-NG": "WifiJammer-NG",
    "KawaiiDeauther": "KawaiiDeauther",
    "Wifi Deauthenticate": "WiFi 断开认证攻击",
    "The FatRat": "The FatRat",
    "Brutal": "Brutal",
    "Stitch": "Stitch",
    "MSFvenom Payload Creator": "MSFvenom 载荷生成器",
    "Venom Shellcode Generator": "Venom Shellcode 生成器",
    "Spycam": "Spycam",
    "Mob-Droid": "Mob-Droid",
    "Enigma": "Enigma",
    "Payload creation tools": "载荷生成工具",
    "Autophisher RK": "Autophisher RK",
    "Pyphisher": "Pyphisher",
    "AdvPhishing": "AdvPhishing",
    "Setoolkit": "Setoolkit",
    "SocialFish": "SocialFish",
    "HiddenEye": "HiddenEye",
    "Evilginx3": "Evilginx3",
    "I-See_You": "I-See_You",
    "SayCheese": "SayCheese",
    "QR Code Jacking": "二维码劫持",
    "BlackEye": "BlackEye",
    "ShellPhish": "ShellPhish",
    "Thanos": "Thanos",
    "QRLJacking": "QRLJacking",
    "Maskphish": "Maskphish",
    "BlackPhish": "BlackPhish",
    "dnstwist": "dnstwist",
    "Phishing attack tools": "钓鱼攻击工具",
    "Vegile - Ghost In The Shell": "Vegile - Ghost In The Shell",
    "Chrome Keylogger": "Chrome 键盘记录器",
    "pwncat-cs (Reverse Shell Handler)": "pwncat-cs（反弹 Shell 管理器）",
    "Sliver (C2 Framework)": "Sliver（C2 框架）",
    "Havoc (C2 Framework)": "Havoc（C2 框架）",
    "PEASS-ng — LinPEAS/WinPEAS (Priv Esc)": "PEASS-ng — LinPEAS/WinPEAS（提权）",
    "Ligolo-ng (Tunneling/Pivoting)": "Ligolo-ng（隧道 / 横向跳板）",
    "Chisel (HTTP Tunnel)": "Chisel（HTTP 隧道）",
    "Evil-WinRM (Windows Remote Shell)": "Evil-WinRM（Windows 远程 Shell）",
    "Mythic (C2 Platform)": "Mythic（C2 平台）",
    "Post exploitation tools": "后渗透工具",
    "Pyshell": "Pyshell",
    "Remote Administrator Tools (RAT)": "远程管理工具（RAT）",
    "Androguard": "Androguard",
    "Apk2Gold": "Apk2Gold",
    "JadX": "JadX",
    "Ghidra (NSA Reverse Engineering)": "Ghidra（NSA 逆向工程框架）",
    "Radare2 (RE Framework)": "Radare2（逆向工程框架）",
    "Reverse engineering tools": "逆向工程工具",
    "Sqlmap tool": "Sqlmap 工具",
    "NoSqlMap": "NoSqlMap",
    "Damn Small SQLi Scanner": "Damn Small SQLi Scanner",
    "Explo": "Explo",
    "Blisqy - Exploit Time-based blind-SQL injection": "Blisqy - 利用时间盲注",
    "Leviathan - Wide Range Mass Audit Toolkit": "Leviathan - 大范围审计工具包",
    "SQLScan": "SQLScan",
    "SQL Injection Tools": "SQL 注入工具",
    "SteganoHide": "SteganoHide",
    "StegnoCracker": "StegnoCracker",
    "StegoCracker": "StegoCracker",
    "Whitespace": "Whitespace",
    "Steganography Tools": "隐写工具",
    "Update Tool or System": "更新工具或系统",
    "Uninstall HackingTool": "卸载 HackingTool",
    "Update or Uninstall | Hackingtool": "更新或卸载 | Hackingtool",
    "Web2Attack": "Web2Attack",
    "Skipfish": "Skipfish",
    "SubDomain Finder": "子域名查找器",
    "CheckURL": "CheckURL",
    "Blazy(Also Find ClickJacking)": "Blazy（也可发现点击劫持）",
    "Sub-Domain TakeOver": "子域接管",
    "Dirb": "Dirb",
    "Nuclei (Vulnerability Scanner)": "Nuclei（漏洞扫描器）",
    "ffuf (Web Fuzzer)": "ffuf（Web 模糊测试器）",
    "Feroxbuster (Directory Brute Force)": "Feroxbuster（目录爆破）",
    "Nikto (Web Server Scanner)": "Nikto（Web 服务器扫描器）",
    "wafw00f (WAF Detector)": "wafw00f（WAF 检测器）",
    "Katana (Web Crawler)": "Katana（网页爬虫）",
    "Gobuster (Dir/DNS/Vhost Brute Force)": "Gobuster（目录 / DNS / Vhost 爆破）",
    "Dirsearch (Web Path Discovery)": "Dirsearch（Web 路径发现）",
    "OWASP ZAP (Web App Scanner)": "OWASP ZAP（Web 应用扫描器）",
    "testssl.sh (TLS/SSL Checker)": "testssl.sh（TLS/SSL 检查器）",
    "Arjun (HTTP Parameter Discovery)": "Arjun（HTTP 参数发现）",
    "Caido (Web Security Auditing)": "Caido（Web 安全审计）",
    "mitmproxy (Intercepting Proxy)": "mitmproxy（拦截代理）",
    "Web Attack tools": "Web 攻击工具",
    "WiFi-Pumpkin": "WiFi-Pumpkin",
    "pixiewps": "pixiewps",
    "Bluetooth Honeypot GUI Framework": "蓝牙蜜罐图形框架",
    "Fluxion": "Fluxion",
    "Wifiphisher": "Wifiphisher",
    "Wifite": "Wifite",
    "EvilTwin": "EvilTwin",
    "Fastssh": "Fastssh",
    "Howmanypeople": "Howmanypeople",
    "Airgeddon (Wireless Attack Suite)": "Airgeddon（无线攻击套件）",
    "hcxdumptool (PMKID Capture)": "hcxdumptool（PMKID 捕获）",
    "hcxtools (PMKID/Hash Conversion)": "hcxtools（PMKID / 哈希转换）",
    "Bettercap (Network/WiFi/BLE MITM)": "Bettercap（网络 / WiFi / BLE 中间人）",
    "Wireless attack tools": "无线攻击工具",
    "Cupp": "Cupp",
    "WordlistCreator": "WordlistCreator",
    "Goblin WordGenerator": "Goblin WordGenerator",
    "Password list (1.4 Billion Clear Text Password)": "密码库（14 亿条明文密码）",
    "Hashcat (Password Cracker)": "Hashcat（密码破解器）",
    "John the Ripper": "John the Ripper",
    "haiti (Hash Type Identifier)": "haiti（哈希类型识别）",
    "Wordlist Generator": "字典生成工具",
    "DalFox (Finder of XSS)": "DalFox（XSS 发现器）",
    "XSS Payload Generator": "XSS 载荷生成器",
    "Extended XSS Searcher and Finder": "增强版 XSS 搜索与发现工具",
    "XSS-Freak": "XSS-Freak",
    "XSpear": "XSpear",
    "XSSCon": "XSSCon",
    "XanXSS": "XanXSS",
    "Advanced XSS Detection Suite": "高级 XSS 检测套件",
    "RVuln": "RVuln",
    "XSS Attack Tools": "XSS 攻击工具",
    # Archived reason
    "Python 2 only — EOL January 2020. Repo unmaintained since 2017.": "仅支持 Python 2，已于 2020 年 1 月停止维护；仓库自 2017 年起无人维护。",
    "Python 2 only (pip2.7/python2.7). Repo archived/unmaintained.": "仅支持 Python 2（pip2.7/python2.7），仓库已归档且无人维护。",
    # Descriptions
    "It automatically overwrites the RAM when the system shuts down\nand also changes your IP address.": "系统关机时会自动覆盖内存，\n并同时更换你的 IP 地址。",
    "How to stay in multi places at the same time.": "让你同时“出现在”多个地点的代理工具。",
    "Open-source security tool for AWS, Azure, GCP, and Kubernetes assessments.": "面向 AWS、Azure、GCP 与 Kubernetes 评估的开源安全工具。",
    "Multi-cloud security auditing tool for AWS, Azure, GCP, Alibaba, and Oracle.": "适用于 AWS、Azure、GCP、阿里云和 Oracle 的多云安全审计工具。",
    "AWS exploitation framework for offensive security testing of AWS environments.": "用于 AWS 环境攻防测试的利用框架。",
    "Comprehensive vulnerability scanner for containers, Kubernetes, IaC, and code.": "面向容器、Kubernetes、IaC 和代码的综合漏洞扫描器。",
    "Tools for cloud infrastructure security assessment and exploitation.": "用于云基础设施安全评估与利用的工具。",
    "Uses graph theory to reveal hidden attack paths in Active Directory/Azure environments.": "利用图论揭示活动目录 / Azure 环境中的隐藏攻击路径。",
    "Swiss army knife for pentesting Windows/AD networks. Successor to CrackMapExec.": "用于 Windows / 活动目录网络渗透的瑞士军刀工具，也是 CrackMapExec 的继任者。",
    "Python classes for working with SMB, MSRPC, Kerberos, LDAP, and more.": "提供用于处理 SMB、MSRPC、Kerberos、LDAP 等协议的 Python 类库。",
    "LLMNR/NBT-NS/MDNS poisoner with rogue authentication servers for credential capture.": "通过伪造认证服务进行凭据捕获的 LLMNR/NBT-NS/MDNS 投毒工具。",
    "Active Directory Certificate Services enumeration and abuse tool.": "用于枚举和利用活动目录证书服务的工具。",
    "Kerberos pre-auth brute-forcer for username enumeration and password spraying.": "用于用户名枚举和密码喷洒的 Kerberos 预认证暴力破解工具。",
    "Tools for AD enumeration, attack path discovery, and credential attacks.": "用于活动目录枚举、攻击路径发现和凭据攻击的工具。",
    "Best DDoS Attack Script With 36 Plus Methods. DDoS attacks for SECURITY TESTING PURPOSES ONLY!": "集成 36+ 种方式的 DDoS 脚本，仅限安全测试用途。",
    "Slowloris is basically an HTTP Denial of Service attack. It sends lots of HTTP requests.": "Slowloris 本质上是一种 HTTP 拒绝服务攻击，会持续发送大量 HTTP 请求。",
    "aSYNcrone is a C language based, multifunction SYN Flood DDoS Weapon.\nDisable the destination system by sending SYN packets intensively.": "aSYNcrone 是基于 C 语言的多功能 SYN Flood 工具。\n通过密集发送 SYN 数据包使目标系统失效。",
    "UFONet is a free software, P2P and cryptographic disruptive toolkit that allows performing DoS and DDoS attacks.": "UFONet 是一个自由、点对点、带加密能力的干扰工具包，可执行 DoS 与 DDoS 攻击。",
    "GoldenEye is a python3 app for SECURITY TESTING PURPOSES ONLY!\nGoldenEye is a HTTP DoS Test Tool.\nUsage: ./goldeneye.py <url> [OPTIONS]": "GoldenEye 是仅限安全测试用途的 Python3 HTTP DoS 测试工具。\n用法：./goldeneye.py <url> [OPTIONS]",
    "A Python DDoS script for SECURITY TESTING PURPOSES ONLY.": "仅限安全测试用途的 Python DDoS 脚本。",
    "The RouterSploit Framework is an open-source exploitation framework dedicated to embedded devices": "RouterSploit 是专注于嵌入式设备的开源利用框架。",
    "Websploit is an advanced MITM framework.": "Websploit 是一款高级中间人攻击框架。",
    "Automated All-in-One OS command injection and exploitation tool.\nCommix can be used from web developers, penetration testers or even security researchers\n in order to test web-based applications with the view to find bugs,\n errors or vulnerabilities related to command injection attacks.\n Usage: python commix.py [option(s)]": "自动化一体式操作系统命令注入与利用工具。\nCommix 适合 Web 开发者、渗透测试人员和安全研究员，用于测试 Web 应用中的命令注入漏洞。\n用法：python commix.py [option(s)]",
    "Autopsy is a platform that is used by Cyber Investigators.\n[!] Works in any OS\n[!] Recover Deleted Files from any OS & Media \n[!] Extract Image Metadata": "Autopsy 是面向数字取证调查人员的平台。\n[!] 支持多种操作系统\n[!] 可从各类系统和介质中恢复已删除文件\n[!] 可提取镜像元数据",
    "Wireshark is a network capture and analyzer \ntool to see what’s happening in your network.\n And also investigate Network related incident": "Wireshark 是网络抓包与分析工具，\n可用于观察网络中正在发生的情况，\n也可用于调查网络相关事件。",
    "Extract useful information without parsing the file system": "无需解析文件系统即可提取有用信息。",
    "Guymager is a free forensic imager for media acquisition.": "Guymager 是用于介质采集的免费取证镜像工具。",
    "Toolsley got more than ten useful tools for investigation.\n[+]File signature verifier\n[+]File identifier \n[+]Hash & Validate \n[+]Binary inspector \n [+]Encode text \n[+]Data URI generator \n[+]Password generator": "Toolsley 内置十余种实用调查工具。\n[+] 文件签名校验\n[+] 文件识别\n[+] 哈希计算与校验\n[+] 二进制检查\n[+] 文本编码\n[+] Data URI 生成\n[+] 密码生成",
    "The world's most widely used memory forensics framework.\nUsage: python3 vol.py -f memory.dmp windows.pslist": "全球最常用的内存取证框架。\n用法：python3 vol.py -f memory.dmp windows.pslist",
    "Analyze, reverse engineer, and extract firmware images.\nUsage: binwalk -e firmware.bin": "用于分析、逆向并提取固件镜像。\n用法：binwalk -e firmware.bin",
    "Monitor Linux processes without root — detects cron jobs, scheduled tasks, other users' commands.": "无需 root 即可监控 Linux 进程，可发现定时任务、计划任务和其他用户执行的命令。",
    "Free and open source utility for network discovery and security auditing": "免费开源的网络发现与安全审计工具。",
    "Dracnmap is an open source program which is using to \nexploit the network and gathering information with nmap help.": "Dracnmap 是一个开源程序，借助 nmap 进行网络利用与信息收集。",
    "Xerosploit is a penetration testing toolkit whose goal is to perform\nman-in-the-middle attacks for testing purposes": "Xerosploit 是一个渗透测试工具包，主要用于执行中间人攻击测试。",
    "All in one tool for Information Gathering and Vulnerability Scanning.": "一体化的信息收集与漏洞扫描工具。",
    "ReconSpider is most Advanced Open Source Intelligence (OSINT) Framework for scanning IP Address, Emails, \nWebsites, Organizations and find out information from different sources.\n": "ReconSpider 是高级开源情报（OSINT）框架，可扫描 IP、邮箱、网站和组织，并从多种来源挖掘信息。\n",
    "Check Website Is Online or Not": "检查网站是否在线。",
    "Infoga is a tool gathering email accounts information\n(ip, hostname, country,...) from different public source": "Infoga 可从不同公开来源收集邮箱账户信息\n（IP、主机名、国家等）。",
    "ReconDog Information Gathering Suite": "ReconDog 信息收集套件。",
    "Recon & Vulnerability Scanning Suite": "侦察与漏洞扫描套件。",
    "SecretFinder - A python script for find sensitive data \nlike apikeys, accesstoken, authorizations, jwt,..etc \n and search anything on javascript files.\n\n Usage: python SecretFinder.py -h": "SecretFinder 是一个用于发现敏感信息的 Python 脚本，\n可搜索 API Key、访问令牌、授权信息、JWT 等内容，\n并在 JavaScript 文件中进行检索。\n\n用法：python SecretFinder.py -h",
    "Get ports, vulnerabilities, information, banners,..etc \n for any IP with Shodan (no apikey! no rate limit!)\n[X] Don't use this tool because your ip will be blocked by Shodan!": "可通过 Shodan 查询任意 IP 的端口、漏洞、Banner 等信息（无需 API Key、无速率限制）。\n[X] 不建议使用该工具，否则你的 IP 可能被 Shodan 封禁！",
    "rang3r is a python script which scans in multi thread\n all alive hosts within your range that you specify.": "rang3r 是一个多线程 Python 脚本，可扫描你指定范围内所有存活主机。",
    "An advanced multithreaded admin panel finder written in python.": "使用 Python 编写的高级多线程后台面板查找器。",
    "Gather emails, names, subdomains, IPs and URLs from public sources.\nUsage: theHarvester -d example.com -b all": "从公开来源收集邮箱、姓名、子域、IP 和 URL。\n用法：theHarvester -d example.com -b all",
    "In-depth subdomain enumeration and attack surface mapping.\nUsage: amass enum -d example.com": "深度子域枚举与攻击面测绘。\n用法：amass enum -d example.com",
    "Fastest internet port scanner — 10 million packets/sec.\nUsage: masscan -p1-65535 <IP> --rate=1000": "高速端口扫描器，每秒可发出约千万个数据包。\n用法：masscan -p1-65535 <IP> --rate=1000",
    "Scans all 65k ports in 3 seconds, passes results to nmap automatically.\nUsage: rustscan -a <IP> -- -sV": "约 3 秒扫描全部 65535 个端口，并自动将结果交给 nmap 深挖。\n用法：rustscan -a <IP> -- -sV",
    "Check if an email address is registered on 120+ websites.\nUsage: holehe user@example.com": "检查一个邮箱是否在 120+ 个网站上注册过。\n用法：holehe user@example.com",
    "Collect a dossier on a person by username across 3000+ sites.\nUsage: maigret <username>": "通过用户名在 3000+ 个站点上收集目标资料。\n用法：maigret <username>",
    "Fast multi-purpose HTTP probing tool.\nUsage: httpx -l urls.txt -status-code -title -tech-detect": "快速多用途 HTTP 探测工具。\n用法：httpx -l urls.txt -status-code -title -tech-detect",
    "Automates OSINT collection for threat intelligence and attack surface mapping.": "自动化 OSINT 收集，用于威胁情报与攻击面测绘。",
    "Fast passive subdomain enumeration using multiple sources.": "利用多种来源进行快速被动子域枚举。",
    "Find, verify, and analyze leaked credentials across git repos, S3 buckets, filesystems.": "在 Git 仓库、S3 存储桶和文件系统中查找、验证并分析泄露凭据。",
    "Fast secret scanner for git repos — detects hardcoded passwords, API keys, tokens.": "面向 Git 仓库的高速密钥扫描器，可检测硬编码密码、API Key 和令牌。",
    "All-in-one mobile app pentesting, malware analysis, and security assessment.": "一体化移动应用渗透测试、恶意软件分析与安全评估工具。",
    "Dynamic instrumentation toolkit for runtime hooking on Android, iOS, Windows, macOS, Linux.": "支持安卓、iOS、Windows、macOS、Linux 的运行时动态插桩工具。",
    "Runtime mobile exploration toolkit powered by Frida — no jailbreak/root required.": "基于 Frida 的移动应用运行时探索工具，无需越狱或 root。",
    "Tools for Android/iOS application security testing and analysis.": "用于安卓 / iOS 应用安全测试与分析的工具。",
    "HatCloud build in Ruby. It makes bypass in CloudFlare for discover real IP.": "HatCloud 基于 Ruby 编写，用于绕过 CloudFlare 发现真实 IP。",
    "Android Keylogger + Reverse Shell\n[!] You have to install Some Manually Refer Below Link:\n [+] https://github.com/F4dl0/keydroid": "Android 键盘记录器 + 反向 Shell。\n[!] 需要手动安装部分依赖，参见：\n [+] https://github.com/F4dl0/keydroid",
    "Script that generates an Android App to hack SMS through WAN \n[!] You have to install Some Manually Refer Below Link:\n\t [+] https://github.com/papusingh2sms/mysms": "生成用于通过广域网劫持短信的 Android 应用脚本。\n[!] 需要手动安装部分依赖，参见：\n\t [+] https://github.com/papusingh2sms/mysms",
    "Lockphish it's the first tool for phishing attacks on the lock screen, designed to\n Grab Windows credentials,Android PIN and iPhone Passcode using a https link.": "Lockphish 是首个针对锁屏界面的钓鱼工具，可通过 HTTPS 链接诱导获取 Windows 凭据、Android PIN 和 iPhone 密码。",
    "Powerful Tool For Grab Front Camera Snap Using A Link": "通过链接抓取前置摄像头照片的工具。",
    "EvilApp is a script to generate Android App that can hijack authenticated sessions in cookies.": "EvilApp 可生成 Android 应用，用于劫持 Cookie 中已认证的会话。",
    "KnockMail Tool Verify If Email Exists": "用于验证邮箱是否存在的工具。",
    "Features: \n Automatic hash type identification \n Supports MD5, SHA1, SHA256, SHA384, SHA512": "特性：\n 自动识别哈希类型\n 支持 MD5、SHA1、SHA256、SHA384、SHA512",
    "Generate unicode evil domains for IDN Homograph Attack and detect them.": "生成用于 IDN 同形异义攻击的 Unicode 域名并进行检测。",
    "Terminal Multiplexer (tilix) is a tiling terminal emulator that allows opening several terminal sessions inside one window.": "Terminal Multiplexer（tilix）是一款平铺式终端模拟器，可在同一窗口中打开多个终端会话。",
    "A tool for extracting and filtering URLs, IPs, domains, and subdomains\nfrom web pages or text, with built-in web scraping capabilities.\nSee: python3 crivo_cli.py -h": "用于从网页或文本中提取并过滤 URL、IP、域名和子域的工具，内置网页抓取能力。\n参见：python3 crivo_cli.py -h",
    "Debinject is a tool that inject malicious code into *.debs": "Debinject 用于向 *.deb 软件包中注入恶意代码。",
    "Pixload -- Image Payload Creating tools \n Pixload is Set of tools for creating/injecting payload into images.": "Pixload 是一组图像载荷创建 / 注入工具。\n可用于把载荷写入图像文件。",
    "Brute force attack against Instagram": "针对 Instagram 的暴力破解攻击。",
    "Brute_Force_Attack Gmail Hotmail Twitter Facebook Netflix \n[!] python3 Brute_Force.py -g <Account@gmail.com> -l <File_list>": "针对 Gmail、Hotmail、Twitter、Facebook、Netflix 的暴力破解工具。\n[!] python3 Brute_Force.py -g <Account@gmail.com> -l <File_list>",
    "Facebook BruteForcer": "Facebook 暴力破解器。",
    "Tool to check if an app is installed on the target device through a link.": "通过链接检查目标设备是否安装某个应用的工具。",
    "A Social Media Mapping Tool that correlates profiles\n via facial recognition across different sites.": "通过人脸识别在不同站点之间关联账号资料的社交媒体映射工具。",
    "Find usernames across over 75 social networks": "在 75+ 个社交网络中查找指定用户名。",
    "Hunt down social media accounts by username across social networks \n For More Usage \n\t >>python3 sherlock --help": "根据用户名在多个社交平台上定位账号。\n更多用法：\n\t >>python3 sherlock --help",
    "Check email address and username availability on online platforms with 100% accuracy": "高精度检查邮箱地址和用户名在各平台上的可用性。",
    "Gospider - Fast web spider written in Go": "Gospider 是使用 Go 编写的高速网页爬虫。",
    "Continuously jam all wifi clients and access points within range.": "持续干扰范围内所有 WiFi 客户端和接入点。",
    "Kawaii Deauther is a pentest toolkit whose goal is to perform \n jam on WiFi clients/routers and spam many fake AP for testing purposes.": "Kawaii Deauther 是一个渗透测试工具包，目标是在测试中干扰 WiFi 客户端 / 路由器，并投放大量伪造 AP。",
    "TheFatRat provides an easy way to create backdoors and payloads which can bypass most anti-virus.": "TheFatRat 提供了简便方式来生成后门和载荷，并可绕过多数杀毒软件。",
    "Brutal is a toolkit to quickly create various payloads, powershell attacks, virus attacks and launch listener for a Human Interface Device.": "Brutal 是一套快速生成多种载荷、PowerShell 攻击、病毒攻击并启动 HID 监听器的工具集。",
    "Stitch is a Cross Platform Python Remote Administrator Tool.\n[!] Refer to the project link for Windows & macOS support.": "Stitch 是跨平台的 Python 远程管理工具。\n[!] Windows 与 macOS 支持情况请参考项目主页。",
    "MSFvenom Payload Creator (MSFPC) is a wrapper to generate multiple types of payloads, based on user choice.": "MSFvenom Payload Creator（MSFPC）是一个包装器，可根据用户选择生成多种类型的载荷。",
    "Venom exploits apache2 webserver to deliver LAN payloads via fake webpages.": "Venom 借助 apache2 Web 服务器通过伪造网页投递局域网载荷。",
    "Generates a Win32 payload that captures webcam images every 1 minute.": "生成一个每分钟抓取一次摄像头图像的 Win32 载荷。",
    "Generates metasploit payloads easily without typing long commands.": "无需输入冗长命令即可快速生成 Metasploit 载荷。",
    "Enigma is a Multiplatform payload dropper.": "Enigma 是跨平台载荷投递器。",
    "Automated Phishing Toolkit": "自动化钓鱼工具包。",
    "Easy to use phishing tool with 77 website templates": "易用的钓鱼工具，内置 77 个网站模板。",
    "This is Advance Phishing Tool ! OTP PHISHING": "高级钓鱼工具，支持 OTP 钓鱼。",
    "The Social-Engineer Toolkit is an open-source penetration\ntesting framework designed for social engineering.": "Social-Engineer Toolkit 是专为社会工程学设计的开源渗透测试框架。",
    "Automated Phishing Tool & Information Collector NOTE: username is 'root' and password is 'pass'": "自动化钓鱼与信息收集工具。注意：默认用户名为 'root'，密码为 'pass'。",
    "Modern Phishing Tool With Advanced Functionality And Multiple Tunnelling Services\n\t[!] https://github.com/DarkSecDevelopers/HiddenEye": "现代化钓鱼工具，具备高级功能和多种隧道服务支持。\n\t[!] https://github.com/DarkSecDevelopers/HiddenEye",
    "evilginx is a man-in-the-middle attack framework used for phishing login credentials\nalong with session cookies, bypassing 2-factor authentication.\nRequires Go >= 1.18 installed.": "evilginx 是中间人攻击框架，可用于钓取登录凭据和会话 Cookie，并绕过双因素认证。\n需要安装 Go >= 1.18。",
    "[!] ISeeYou finds the exact location of a target via social engineering.\n[!] Expose local servers to the internet and decode location from log file.": "[!] ISeeYou 可通过社会工程学获取目标的精确位置。\n[!] 它会把本地服务暴露到互联网，并从日志文件中解析位置信息。",
    "Take webcam shots from target just by sending a malicious link": "仅通过发送恶意链接即可抓取目标的摄像头画面。",
    "QR Code Jacking (Any Website)": "二维码劫持（适用于任意网站）。",
    "The ultimate phishing tool with 38 websites available!": "终极钓鱼工具，内置 38 个网站模板！",
    "Phishing Tool for 18 social media": "针对 18 个社交媒体平台的钓鱼工具。",
    "Browser to Browser Phishing toolkit": "浏览器到浏览器的钓鱼工具包。",
    "QRLJacking — session hijacking attack vector targeting QR code based login": "QRLJacking 是面向二维码登录场景的会话劫持攻击向量。",
    "Hide phishing URL under a normal looking URL (google.com or facebook.com)": "把钓鱼 URL 伪装成正常外观的地址（如 google.com 或 facebook.com）。",
    "Domain name permutation engine for detecting typosquatting, phishing and brand impersonation": "用于检测域名抢注、钓鱼和品牌仿冒的域名变体引擎。",
    "This tool will set up your backdoor/rootkits when backdoor is already setup it will be \nhidden your specific process,unlimited your session in metasploit and transparent.": "该工具可部署后门 / Rootkit；当后门已存在时，还可隐藏指定进程、延长 Metasploit 会话并提高隐蔽性。",
    "Hera Chrome Keylogger": "Hera Chrome 键盘记录器。",
    "Post-exploitation platform — manages reverse/bind shells with automation.\nHandles file upload/download, persistence, privilege escalation.\nUsage: pwncat-cs -lp 4444": "后渗透平台，可自动化管理反弹 / 绑定 Shell。\n支持文件上传下载、持久化和提权。\n用法：pwncat-cs -lp 4444",
    "Cross-platform adversary emulation/red team C2 framework — mTLS, HTTP(S), DNS, WireGuard.": "跨平台对手模拟 / 红队 C2 框架，支持 mTLS、HTTP(S)、DNS、WireGuard。",
    "Modern post-exploitation C2 framework with EDR evasion. Cobalt Strike alternative.": "现代化后渗透 C2 框架，具备 EDR 规避能力，可视作 Cobalt Strike 的替代方案。",
    "Privilege escalation enumeration scripts for Linux and Windows.": "适用于 Linux 与 Windows 的提权枚举脚本集。",
    "Advanced tunneling/pivoting tool using TUN interfaces — no SOCKS needed.": "基于 TUN 接口的高级隧道 / 横向移动工具，无需 SOCKS。",
    "Fast TCP/UDP tunnel over HTTP, secured via SSH — pivoting and port forwarding.": "通过 HTTP 建立快速 TCP/UDP 隧道，并使用 SSH 加固，适合横向跳板与端口转发。",
    "Ultimate WinRM shell for hacking/pentesting Windows machines.": "用于攻击 / 渗透 Windows 主机的强大 WinRM Shell。",
    "Collaborative, multi-payload C2 platform designed for red team operations.": "面向红队行动的协作式多载荷 C2 平台。",
    "Pyshell is a Rat Tool that can be able to download & upload files,\n Execute OS Command and more..": "Pyshell 是一款 RAT 工具，支持上传 / 下载文件、执行系统命令等功能。",
    "Androguard is a Reverse engineering, Malware and goodware analysis of Android applications and more": "Androguard 用于 Android 应用的逆向分析、恶意与良性样本分析等工作。",
    "Apk2Gold is a CLI tool for decompiling Android apps to Java": "Apk2Gold 是将 Android 应用反编译为 Java 的命令行工具。",
    "Jadx is Dex to Java decompiler.\n[*] decompile Dalvik bytecode to java classes from APK, dex, aar and zip files\n[*] decode AndroidManifest.xml and other resources from resources.arsc": "Jadx 是 Dex 到 Java 的反编译器。\n[*] 可把 APK、dex、aar、zip 中的 Dalvik 字节码反编译为 Java 类\n[*] 可解析 AndroidManifest.xml 及 resources.arsc 中的其他资源",
    "NSA's software reverse engineering framework — disassembly, decompilation, scripting.": "NSA 推出的软件逆向工程框架，支持反汇编、反编译和脚本扩展。",
    "Portable UNIX-like reverse engineering framework and command-line toolset.": "可移植的类 UNIX 逆向工程框架与命令行工具集。",
    "sqlmap is an open source penetration testing tool that automates the process of detecting and exploiting SQL injection flaws and taking over database servers. [!] python3 sqlmap.py -u [http://example.com] --batch --banner. More usage: https://github.com/sqlmapproject/sqlmap/wiki/Usage": "sqlmap 是开源渗透测试工具，可自动发现并利用 SQL 注入漏洞，甚至接管数据库服务器。\n[!] python3 sqlmap.py -u [http://example.com] --batch --banner\n更多用法：https://github.com/sqlmapproject/sqlmap/wiki/Usage",
    "NoSQLMap is an open source Python tool designed to audit and automate injection attacks. [*] Please install MongoDB.": "NoSQLMap 是用于审计和自动化注入攻击的开源 Python 工具。\n[*] 请先安装 MongoDB。",
    "DSSS is a fully functional SQL injection vulnerability scanner also supporting GET and POST parameters. Usage: python3 dsss.py -h | -u [URL]": "DSSS 是功能完整的 SQL 注入漏洞扫描器，支持 GET 和 POST 参数。\n用法：python3 dsss.py -h | -u [URL]",
    "Explo is a simple tool to describe web security issues in human and machine readable format. Usage: explo [--verbose|-v] testcase.yaml | explo [--verbose|-v] examples/*.yaml": "Explo 可用人类和机器都能读取的格式描述 Web 安全问题。\n用法：explo [--verbose|-v] testcase.yaml | explo [--verbose|-v] examples/*.yaml",
    "Blisqy helps web security researchers find time-based blind SQL injections on HTTP headers and exploit them.": "Blisqy 帮助研究人员在 HTTP 头中发现并利用基于时间的盲注。",
    "Leviathan is a mass audit toolkit with service discovery, brute force, SQL injection detection, and custom exploit capabilities. Requires API keys.": "Leviathan 是大规模审计工具包，集成服务发现、暴力破解、SQL 注入检测和自定义利用能力。\n需要 API Key。",
    "SQLScan is a quick web scanner to find SQL injection points. Not for educational purposes.": "SQLScan 是用于快速发现 SQL 注入点的 Web 扫描器，不适合教学用途。",
    "SteganoCracker uncovers hidden data inside files using brute-force utility": "SteganoCracker 使用暴力破解方式挖掘文件中的隐藏数据。",
    "StegoCracker lets you hide and retrieve data in image or audio files": "StegoCracker 可在图像或音频文件中隐藏并提取数据。",
    "Use whitespace and unicode characters for steganography": "利用空白字符和 Unicode 字符进行隐写。",
    "Update system packages or pull the latest hackingtool code": "更新系统软件包，或拉取最新的 hackingtool 代码。",
    "Remove hackingtool from system": "从系统中移除 hackingtool。",
    "Web hacking framework with tools, exploits by python": "使用 Python 编写的 Web 攻击框架，集成工具与利用模块。",
    "Skipfish – Fully automated, active web application security reconnaissance tool \n Usage: skipfish -o [FolderName] targetip/site": "Skipfish 是全自动、主动式 Web 应用安全侦察工具。\n用法：skipfish -o [FolderName] targetip/site",
    "Sublist3r is a python tool designed to enumerate subdomains of websites using OSINT \n Usage:\n\t[1] python3 sublist3r.py -d example.com \n[2] python3 sublist3r.py -d example.com -p 80,443": "Sublist3r 是使用 OSINT 枚举网站子域名的 Python 工具。\n用法：\n\t[1] python3 sublist3r.py -d example.com \n[2] python3 sublist3r.py -d example.com -p 80,443",
    "Detect evil urls that uses IDN Homograph Attack.\n\t[!] python3 checkURL.py --url google.com": "检测使用 IDN 同形异义攻击的恶意 URL。\n\t[!] python3 checkURL.py --url google.com",
    "Blazy is a modern login page bruteforcer": "Blazy 是现代化登录页暴力破解器。",
    "Sub-domain takeover vulnerability occur when a sub-domain \n (subdomain.example.com) is pointing to a service (e.g: GitHub, AWS/S3,..)\nthat has been removed or deleted.\nUsage:python3 takeover.py -d www.domain.com -v": "当子域（如 subdomain.example.com）指向已被删除的服务（如 GitHub、AWS/S3 等）时，就会产生子域接管漏洞。\n用法：python3 takeover.py -d www.domain.com -v",
    "DIRB is a Web Content Scanner. It looks for existing (and/or hidden) Web Objects.\nIt basically works by launching a dictionary based attack against \n a web server and analyzing the response.": "DIRB 是 Web 内容扫描器，用于查找已存在或隐藏的 Web 资源。\n它通过字典攻击 Web 服务器并分析响应来工作。",
    "Fast, template-based vulnerability scanner used by 50k+ security teams.\nUsage: nuclei -u https://example.com": "高速模板化漏洞扫描器，被 5 万+ 安全团队使用。\n用法：nuclei -u https://example.com",
    "Fast web fuzzer — content discovery, parameter fuzzing, vhost discovery.\nUsage: ffuf -w wordlist.txt -u https://example.com/FUZZ": "高速 Web 模糊测试工具，支持内容发现、参数模糊测试和 vhost 发现。\n用法：ffuf -w wordlist.txt -u https://example.com/FUZZ",
    "Fast, recursive content discovery tool written in Rust.\nUsage: feroxbuster -u https://example.com -w wordlist.txt": "使用 Rust 编写的高速递归内容发现工具。\n用法：feroxbuster -u https://example.com -w wordlist.txt",
    "Scan web servers for dangerous files, outdated software, misconfigurations.\nUsage: nikto -h https://example.com": "扫描 Web 服务器中的危险文件、过时软件和错误配置。\n用法：nikto -h https://example.com",
    "Fingerprint and identify Web Application Firewalls (WAF).\nUsage: wafw00f https://example.com": "识别并指纹化 Web 应用防火墙（WAF）。\n用法：wafw00f https://example.com",
    "Next-generation crawling and spidering framework from ProjectDiscovery.\nUsage: katana -u https://example.com": "ProjectDiscovery 推出的新一代爬取与蜘蛛框架。\n用法：katana -u https://example.com",
    "Directory/file, DNS, and vhost brute-forcing tool written in Go.": "使用 Go 编写的目录 / 文件、DNS 与 vhost 爆破工具。",
    "Web path brute-forcing tool for discovering directories and files on web servers.": "用于发现 Web 服务器目录和文件的路径爆破工具。",
    "Full-featured web application security scanner — proxy, spider, fuzzer, scanner.": "功能完整的 Web 应用安全扫描器，集成代理、爬虫、模糊测试和扫描能力。",
    "Check TLS/SSL ciphers, protocols, and cryptographic flaws on any port.": "检查任意端口上的 TLS/SSL 加密套件、协议与密码学缺陷。",
    "HTTP parameter discovery suite that finds hidden GET/POST parameters.": "用于发现隐藏 GET/POST 参数的 HTTP 参数探测工具集。",
    "Lightweight, modern web security auditing toolkit — Burp Suite alternative written in Rust.": "轻量现代的 Web 安全审计工具包，可视为 Rust 编写的 Burp Suite 替代品。",
    "Interactive TLS-capable intercepting HTTP proxy for pentesters and developers.": "支持 TLS 的交互式 HTTP 拦截代理，适合渗透测试人员和开发者。",
    "The WiFi-Pumpkin is a rogue AP framework to easily create fake networks\nwhile forwarding legitimate traffic to and from the unsuspecting target.": "WiFi-Pumpkin 是伪造 AP 框架，可轻松创建假网络，同时转发目标与真实网络之间的流量。",
    "Pixiewps is a tool written in C used to bruteforce offline the WPS pin\nexploiting the low or non-existing entropy of some Access Points (pixie dust attack).": "Pixiewps 是用 C 编写的工具，可利用某些 AP 的低熵或无熵特性离线爆破 WPS PIN（pixie dust 攻击）。",
    "You need at least 1 bluetooth receiver.\nInstall libbluetooth-dev (Ubuntu) / bluez-libs-devel (Fedora) / bluez-devel (openSUSE).": "至少需要 1 个蓝牙接收器。\n请安装 libbluetooth-dev（Ubuntu）/ bluez-libs-devel（Fedora）/ bluez-devel（openSUSE）。",
    "Fluxion is a remake of linset by vk496 with enhanced functionality.": "Fluxion 是对 vk496 的 linset 的重制版，功能更强。",
    "Wifiphisher is a rogue Access Point framework for conducting red team engagements\nor Wi-Fi security testing. Easily achieve man-in-the-middle position against\nwireless clients by performing targeted Wi-Fi association attacks.": "Wifiphisher 是用于红队演练和 Wi-Fi 安全测试的伪造 AP 框架。\n可通过定向的 Wi-Fi 关联攻击，轻松对无线客户端取得中间人位置。",
    "Wifite is an automated wireless attack tool.": "Wifite 是自动化无线攻击工具。",
    "Fakeap — perform Evil Twin Attack by getting credentials using a Fake page and Fake Access Point.": "Fakeap 可通过伪造页面和伪造接入点执行 Evil Twin 攻击并窃取凭据。",
    "Fastssh — multi-threaded scan and brute force attack against SSH protocol\nusing the most commonly used credentials.": "Fastssh 是针对 SSH 协议的多线程扫描和暴力破解工具，使用常见凭据组合进行尝试。",
    "Count the number of people around you by monitoring wifi signals.\n[@] WIFI ADAPTER REQUIRED\n[*] It may be illegal to monitor networks for MAC addresses on networks you do not own.": "通过监控 WiFi 信号统计你周围的人数。\n[@] 需要 WiFi 网卡\n[*] 监控非自有网络的 MAC 地址在某些地区可能违法。",
    "Multi-use bash script for auditing wireless networks.\nCovers WPA/WPA2, WEP, WPS, PMKID, evil twin, handshake capture and more.": "多用途 Bash 脚本，用于审计无线网络。\n覆盖 WPA/WPA2、WEP、WPS、PMKID、Evil Twin、握手包捕获等场景。",
    "Capture packets and PMKID hashes from WLAN devices.\nUsage: hcxdumptool -i <iface> -o capture.pcapng --enable_status=1": "从 WLAN 设备捕获数据包和 PMKID 哈希。\n用法：hcxdumptool -i <iface> -o capture.pcapng --enable_status=1",
    "Convert captured WLAN packets to hashcat/JtR-compatible format.\nUsage: hcxpcapngtool -o hashes.txt capture.pcapng": "把捕获到的 WLAN 数据包转换为 hashcat / JtR 可识别格式。\n用法：hcxpcapngtool -o hashes.txt capture.pcapng",
    "Swiss army knife for WiFi, BLE, HID, and Ethernet network recon and MITM attacks.": "用于 WiFi、BLE、HID 和以太网侦察及中间人攻击的瑞士军刀工具。",
    "Common User Passwords Profiler — generates personalized wordlists based on target info.": "通用用户密码画像工具，可根据目标信息生成个性化字典。",
    "WlCreator is a C program that can create all possibilities of passwords,\n and you can choose Length, Lowercase, Capital, Numbers and Special Chars": "WlCreator 是一个 C 程序，可生成各种密码组合，\n并可自定义长度、小写字母、大写字母、数字和特殊字符。",
    "Goblin WordGenerator": "Goblin WordGenerator 字典生成工具。",
    "This tool allows you to perform OSINT and reconnaissance on an organisation or an individual. It allows one to search 1.4 Billion clear text credentials which was dumped as part of BreachCompilation leak. This database makes finding passwords faster and easier than ever before.": "该工具可用于针对组织或个人开展 OSINT 与侦察。\n它允许你搜索 BreachCompilation 泄露事件中的 14 亿条明文凭据，让查找密码变得前所未有地快速。",
    "World's fastest GPU/CPU password recovery tool — supports 300+ hash types.\nUsage: hashcat -m 0 -a 0 hashes.txt wordlist.txt": "全球最快的 GPU/CPU 密码恢复工具之一，支持 300+ 种哈希类型。\n用法：hashcat -m 0 -a 0 hashes.txt wordlist.txt",
    "Open-source password security auditing and recovery tool.\nUsage: john --wordlist=wordlist.txt hashfile": "开源密码安全审计与恢复工具。\n用法：john --wordlist=wordlist.txt hashfile",
    "Identify hash types — supports 300+ algorithms.\nUsage: haiti <hash>": "识别哈希类型，支持 300+ 种算法。\n用法：haiti <hash>",
    "XSS Scanning and Parameter Analysis tool.": "XSS 扫描与参数分析工具。",
    "XSS PAYLOAD GENERATOR - XSS SCANNER - XSS DORK FINDER": "XSS 载荷生成器 / XSS 扫描器 / XSS Dork 查找器。",
    "Extended XSS Searcher and Finder": "扩展型 XSS 搜索与发现工具。",
    "An XSS scanner fully written in Python 3 from scratch.": "完全使用 Python 3 从零编写的 XSS 扫描器。",
    "XSpear is an XSS Scanner built on Ruby Gems.": "XSpear 是基于 Ruby Gems 构建的 XSS 扫描器。",
    "Reflected XSS searching tool that creates payloads from templates.": "基于模板生成载荷的反射型 XSS 搜索工具。",
    "XSStrike is a Python-based tool designed to detect and exploit XSS vulnerabilities.": "XSStrike 是基于 Python 的工具，用于检测和利用 XSS 漏洞。",
    "Multi-threaded and Automated Web Vulnerability Scanner written in Rust.": "使用 Rust 编写的多线程自动化 Web 漏洞扫描器。",
}


_ORIGINAL_INPUT = builtins.input
_ORIGINAL_PROMPT_ASK = Prompt.ask.__func__
_ORIGINAL_CONFIRM_ASK = Confirm.ask.__func__


def tr(text: str) -> str:
    return TRANSLATIONS.get(text, text)


def patch_interaction() -> None:
    if not getattr(Prompt, "_ht_zh_patched", False):
        def _prompt_ask(cls, prompt="", **kwargs):
            if isinstance(prompt, str):
                prompt = tr(prompt)
            return _ORIGINAL_PROMPT_ASK(cls, prompt=prompt, **kwargs)

        Prompt.ask = classmethod(_prompt_ask)
        Prompt._ht_zh_patched = True

    if not getattr(Confirm, "_ht_zh_patched", False):
        def _confirm_ask(cls, prompt="", **kwargs):
            if isinstance(prompt, str):
                prompt = tr(prompt)
            return _ORIGINAL_CONFIRM_ASK(cls, prompt=prompt, **kwargs)

        Confirm.ask = classmethod(_confirm_ask)
        Confirm._ht_zh_patched = True

    if not getattr(builtins, "_ht_zh_input_patched", False):
        def _localized_input(prompt=""):
            if isinstance(prompt, str):
                prompt = tr(prompt)
            return _ORIGINAL_INPUT(prompt)

        builtins.input = _localized_input
        builtins._ht_zh_input_patched = True


def patch_console(console) -> None:
    if getattr(console, "_ht_zh_console_patched", False):
        return

    original_print = console.print

    def _localized_print(*args, **kwargs):
        localized_args = tuple(tr(arg) if isinstance(arg, str) else arg for arg in args)
        return original_print(*localized_args, **kwargs)

    console.print = _localized_print
    console._ht_zh_console_patched = True


def localize_tool_tree(items: Iterable[object]) -> None:
    for item in items:
        if getattr(item, "_ht_zh_localized", False):
            continue

        for attr in ("TITLE", "DESCRIPTION", "ARCHIVED_REASON"):
            value = getattr(item, attr, None)
            if isinstance(value, str):
                setattr(item, f"_ORIGINAL_{attr}", value)
                setattr(item, attr, tr(value))

        setattr(item, "_ht_zh_localized", True)

        subtools = getattr(item, "TOOLS", None)
        if isinstance(subtools, list):
            localize_tool_tree(subtools)


def original_text(obj: object, attr: str) -> str:
    return getattr(obj, f"_ORIGINAL_{attr}", getattr(obj, attr, ""))
